package black.white;

import listas.ListaRegistroPersonal;
import logica.Metodos;
import Utilidades.ValidacionesCampos;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import Utilidades.DepartamentosMunicipios;
import java.awt.event.KeyEvent;
import Utilidades.ReportePersonal;

public class GestionarPersonal extends javax.swing.JFrame {

    File Fil;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Imagen", ".jpg");
    String Docum, rutaimagen;
    int swModificar = 0;
    ValidacionesCampos v = new ValidacionesCampos();
    Metodos nuevoPersonal = new Metodos();
    ListaRegistroPersonal listaPersonal;
    DepartamentosMunicipios depaMuni;
    String[] vecDepa, vecMuni;
    ImageIcon imaPregunta = new ImageIcon("C:\\Boutique\\src\\Imagenes\\pregun.jpg");
    ImageIcon imaInforma = new ImageIcon("C:\\Boutique\\src\\Imagenes\\iconoInfor.jpg");

    public GestionarPersonal(ListaRegistroPersonal listaPerson) {  //El constructor..para que cuando se llame el formulario, todo este validado

        initComponents();
        this.listaPersonal = listaPerson;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.ValidarCampos();
        //this.ValidarObligatorios();
        this.DesactivarCampos();
        this.setVisible(true);
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        DateFechadeN.setMaxSelectableDate(new Date());
        DateFechaC.setMaxSelectableDate(new Date());

        depaMuni = new DepartamentosMunicipios();

        vecDepa = depaMuni.cargarDepartamentos();

        for (int j = 0; j < vecDepa.length; j++) {

            this.CombDep.addItem(vecDepa[j]);

        }

        // Se agregan los item a cada combox, para que se despliegue la lista 
        this.combTipoDoc.addItem("Cédula ciudadania");
        this.combTipoDoc.addItem("Cédula Extranjeria");
        this.combTipoDoc.addItem("Pasaporte");

        this.combTipodeS.addItem("A");
        this.combTipodeS.addItem("B");
        this.combTipodeS.addItem("O");
        this.combTipodeS.addItem("AB");

        this.combmasymenos.addItem("+");
        this.combmasymenos.addItem("-");

        this.combEstado.addItem("Activo");
        this.combEstado.addItem("Inactivo");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/iconopersonal.jpg")).getImage());

    }

    private GestionarPersonal() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combTipoDoc = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtDocum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DateFechadeN = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        CombDep = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        CombCiudaddeN = new javax.swing.JComboBox();
        combmasymenos = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        combTipodeS = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtDirecciondeR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefonoF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefonoM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBarrio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTipodeCon = new javax.swing.JTextField();
        DateFechaC = new com.toedter.calendar.JDateChooser();
        combEstado = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar Personal");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Tipo Documento(*)");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Número Documento(*)");

        txtDocum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombres y Apellidos(*)");

        txtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Fecha Nacimiento(*)");

        DateFechadeN.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateFechadeNPropertyChange(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Departamento:");

        CombDep.setEnabled(false);
        CombDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombDepActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Municipio:");

        CombCiudaddeN.setEnabled(false);
        CombCiudaddeN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombCiudaddeNActionPerformed(evt);
            }
        });

        combmasymenos.setEnabled(false);

        jLabel17.setText("Tipo Rh(*)");

        combTipodeS.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Tipo de Sangre(*)");

        jLabel18.setBackground(new java.awt.Color(204, 204, 255));
        jLabel18.setForeground(new java.awt.Color(204, 204, 255));
        jLabel18.setText("imagen");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        btnCargar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCargar.setText("Cargar Imagen");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combTipodeS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CombDep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combmasymenos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CombCiudaddeN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateFechadeN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DateFechadeN, txtDocum});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDocum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DateFechadeN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CombCiudaddeN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combmasymenos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CombDep, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combTipodeS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnCargar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DateFechadeN, txtDocum});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Domicilio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Dirección(*)");

        txtDirecciondeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecciondeRActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Teléfono Fijo(*)");

        txtTelefonoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoFActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Correo Electrónico:");

        txtCorreoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEActionPerformed(evt);
            }
        });
        txtCorreoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoEKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Telefóno Móvil:");

        txtTelefonoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoMActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Barrio:");

        txtBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarrioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirecciondeR, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBarrio)
                            .addComponent(txtTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDirecciondeR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefonoF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Datos Laborales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Cargo(*)");

        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Fecha Contratación(*)");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tipo de Contrato(*)");

        txtTipodeCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipodeConActionPerformed(evt);
            }
        });

        combEstado.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Estado:");

        btnListar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listar.jpg"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipodeCon, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(DateFechaC, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(combEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(txtTipodeCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(DateFechaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnListar)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DateFechaC, txtTipodeCon});

        btnCrear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.jpg"))); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.jpg"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.jpg"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultar.jpg"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.jpg"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/400px-borrar_svg.jpg"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.jpg"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Los Campos marcados con (*) son obligatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1037, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnConsultar, btnCrear, btnEliminar, btnGuardar, btnLimpiar, btnModificar, btnSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnGuardar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsultar, btnCrear, btnEliminar, btnGuardar, btnLimpiar, btnModificar, btnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumActionPerformed

    private void txtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCActionPerformed

    private void txtDirecciondeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecciondeRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecciondeRActionPerformed

    private void txtTelefonoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoFActionPerformed

    private void txtCorreoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEActionPerformed

    private void txtTelefonoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMActionPerformed

    private void txtBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarrioActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtTipodeConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipodeConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipodeConActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        this.ActivarCampos();
        this.LimpiarCampos();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        nuevoPersonal = this.GuardarCampos();
        if (this.ValidarObligatorios().equals("")) {
            if (swModificar == 1) {
                if (listaPersonal.guardarModificacionPersonal(nuevoPersonal)) {

                    JOptionPane.showMessageDialog(this, "Se modificó el empleado correctamente", "Gestionar Personal - S.I.C ",
                            JOptionPane.OK_OPTION, imaInforma);
                    this.LimpiarCampos();
                    this.DesactivarCampos();
                    swModificar = 0;

                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo modificar el empleado correctamente ", "Gestionar Personal - S.I.C ",
                            JOptionPane.OK_OPTION, imaInforma);

                }
            } else {
                if (listaPersonal.siExiste(nuevoPersonal.getDocumento())) {
                    JOptionPane.showMessageDialog(this, "El empleado ya existe", "Gestionar Personal - S.I.C ",
                            JOptionPane.OK_OPTION, imaInforma);

                } else {
                    if (listaPersonal.guardarRegistro(nuevoPersonal)) {
                        JOptionPane.showMessageDialog(this, "Se guardó el empleado correctamente ", "Gestionar Personal - S.I.C ",
                                JOptionPane.OK_OPTION, imaInforma);
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo guardar el empleado", "Gestionar Personal - S.I.C ",
                                JOptionPane.OK_OPTION, imaInforma);
                    }
                    this.LimpiarCampos();
                    this.DesactivarCampos();
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Ingrese los Campos Obligatorios", "Gestionar Personal - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String empleadoaModificar = JOptionPane.showInputDialog(this, "Ingrese el número de documento del empleado");
        if (listaPersonal.siExiste(empleadoaModificar)) {
            nuevoPersonal = listaPersonal.buscarPersonal(empleadoaModificar);     // funcion...porque retorna una variable de tipo metodoscliente
            this.LlenarDatos();
            this.ActivarCampos();
            swModificar = 1;
        } else {
            JOptionPane.showMessageDialog(this, "El documento del empleado ingresado no esta registrado", "Gestionar Personal - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
        }

        txtDocum.setEnabled(false);
        combTipoDoc.setEnabled(false);

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        String documentoaConsultar = JOptionPane.showInputDialog(this, "Ingrese el documento del empleado");
        nuevoPersonal = listaPersonal.buscarPersonal(documentoaConsultar);
        if (nuevoPersonal == null) {
            JOptionPane.showMessageDialog(this, " El número del documento no existe", "Gestionar Personal - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
        } else {

            this.LlenarDatos();
        }

    }//GEN-LAST:event_btnConsultarActionPerformed


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String clienteaEliminar = JOptionPane.showInputDialog(this, "Ingrese el número de documento ha eliminar");
        if (listaPersonal.eliminarPersonal(clienteaEliminar)) {
            JOptionPane.showMessageDialog(this, "Se eliminó el empleado correctamente ", "Gestionar Personal - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
        } else {
            JOptionPane.showMessageDialog(this, "El empleado no existe!", "Gestionar Personal - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
        }
        this.LimpiarCampos();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        this.LimpiarCampos();
        this.DesactivarCampos();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        int opc;
        opc = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir ?",
                "Salir.  S.I.C.", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, imaPregunta);
        if (opc == 0) {
            this.setVisible(false);

        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

        //Crear un objeto JFileChooser
        JFileChooser dlg = new JFileChooser();
        //Del objeto creado llamamos el metodo setFileFilter
        dlg.setFileFilter(filter);
        //Abrir la ventana de dialogo para escojer las imagenes
        int option = dlg.showOpenDialog(this);
        //Si hacemos clic en el boton abrir
        if (option == JFileChooser.APPROVE_OPTION) {
            //Obtener el nombre del archivo seleccionado
            String fil = dlg.getSelectedFile().getPath();
            //Obtener la direccion donde se guarda la imagen
            String file = dlg.getSelectedFile().toString();
            jLabel18.setIcon(new ImageIcon(fil));
            //Modificar la imagen
            ImageIcon icon = new ImageIcon(fil);
            //Extraer la imagen del icono
            Image img = icon.getImage();
            //Cambiar tamaño a la imagen       
            Image newimg = img.getScaledInstance(153, 160, java.awt.Image.SCALE_SMOOTH);
            //Se genera el ImageIcon con la nueva imagen
            ImageIcon newIcon = new ImageIcon(newimg);
            jLabel18.setIcon(newIcon);
            //jLimagen.setSize(153,160);
            //pone la ruta de la imagen en el textbox 1
            jTextField1.setText(file);
            //pone el nombre de la imagen en el textbox 2
            jTextField2.setText(fil);
            rutaimagen = "";
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void CombDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombDepActionPerformed

        if (evt.getSource() == CombDep) {

            CombCiudaddeN.removeAllItems();
            vecMuni = depaMuni.cargarMunicipios(CombDep.getSelectedIndex());
            for (int j = 0; j < 125; j++) {

                if (vecMuni[j] == null) {

                    break;
                } else {

                    CombCiudaddeN.addItem(vecMuni[j]);
                }
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_CombDepActionPerformed

    private void CombCiudaddeNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombCiudaddeNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombCiudaddeNActionPerformed

    private void DateFechadeNPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateFechadeNPropertyChange

    }//GEN-LAST:event_DateFechadeNPropertyChange

    private void txtCorreoEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoEKeyPressed

        if (evt.getSource() == txtCorreoE && evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (!v.validarEmail(txtCorreoE.getText())) {

                JOptionPane.showMessageDialog(null, "No corresponde a un correo electrónico", "Recuperar Contraseña - S.I.C.", JOptionPane.OK_OPTION, null);
                txtCorreoE.requestFocus();
            } else {

                txtCorreoE.transferFocus();
            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEKeyPressed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ReportePersonal rp = new ReportePersonal(listaPersonal.getCabeza());
    }//GEN-LAST:event_btnListarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CombCiudaddeN;
    private javax.swing.JComboBox CombDep;
    private com.toedter.calendar.JDateChooser DateFechaC;
    private com.toedter.calendar.JDateChooser DateFechadeN;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox combEstado;
    private javax.swing.JComboBox combTipoDoc;
    private javax.swing.JComboBox combTipodeS;
    private javax.swing.JComboBox combmasymenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCorreoE;
    private javax.swing.JTextField txtDirecciondeR;
    private javax.swing.JTextField txtDocum;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextField txtTelefonoF;
    private javax.swing.JTextField txtTelefonoM;
    private javax.swing.JTextField txtTipodeCon;
    // End of variables declaration//GEN-END:variables

    public void LimpiarCampos() {
        combTipoDoc.setSelectedItem("");
        txtDocum.setText("");
        txtNombreC.setText("");
        DateFechadeN.setDate(null);
        CombCiudaddeN.setSelectedItem("");
        CombDep.setSelectedItem("");
        combTipodeS.setSelectedItem("");
        combmasymenos.setSelectedItem("");
        txtCargo.setText("");
        DateFechaC.setDate(null);
        txtTipodeCon.setText("");
        txtDirecciondeR.setText("");
        txtBarrio.setText("");
        txtTelefonoF.setText("");
        txtTelefonoM.setText("");
        txtCorreoE.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        combEstado.setSelectedItem("");
        jLabel18.setIcon(null);

    }

    public Metodos GuardarCampos() {
        Metodos p = new Metodos();
        p.setTipodeDocumento((String) combTipoDoc.getSelectedItem());
        p.setDocumento(txtDocum.getText());
        p.setNombreCompleto(txtNombreC.getText());
        p.setFechadeNacimiento(DateFechadeN.getDate());
        p.setCiudaddeNacimiento((String) CombCiudaddeN.getSelectedItem());
        p.setDepartamento((String) CombDep.getSelectedItem());
        p.setTipodeSangre((String) combTipodeS.getSelectedItem());
        p.setFactorRH((String) combmasymenos.getSelectedItem());
        p.setCargo(txtCargo.getText());
        p.setFecha_Contra(DateFechaC.getDate());
        p.setTipodeContrato(txtTipodeCon.getText());
        p.setDirecciondeResidencia(txtDirecciondeR.getText());
        p.setBarrio(txtBarrio.getText());
        p.setTelefonoFijo(txtTelefonoF.getText());
        p.setTelefonoMovil(txtTelefonoM.getText());
        p.setCorreoElectronico(txtCorreoE.getText());
        p.setEstado((String) combEstado.getSelectedItem());
        p.setRutaImagen(jTextField1.getText());
        p.setNombreImg(jTextField2.getText());
        return p;
    }

    public void LlenarDatos() {
        combTipoDoc.setSelectedItem(nuevoPersonal.getTipodeDocumento());
        txtDocum.setText(nuevoPersonal.getDocumento());
        txtNombreC.setText(nuevoPersonal.getNombreCompleto());
        DateFechadeN.setDate(nuevoPersonal.getFechadeNacimiento());
        CombCiudaddeN.setSelectedItem(nuevoPersonal.getCiudaddeNacimiento());
        CombDep.setSelectedItem(nuevoPersonal.getDepartamento());
        combTipodeS.setSelectedItem(nuevoPersonal.getTipodeSangre());
        combmasymenos.setSelectedItem(nuevoPersonal.getFactorRH());
        txtCargo.setText(nuevoPersonal.getCargo());
        DateFechaC.setDate(nuevoPersonal.getFecha_Contra());
        txtTipodeCon.setText(nuevoPersonal.getTipodeContrato());
        txtDirecciondeR.setText(nuevoPersonal.getDirecciondeResidencia());
        txtBarrio.setText(nuevoPersonal.getBarrio());
        txtTelefonoF.setText(nuevoPersonal.getTelefonoFijo());
        txtTelefonoM.setText(nuevoPersonal.getTelefonoMovil());
        txtCorreoE.setText(nuevoPersonal.getCorreoElectronico());
        combEstado.setSelectedItem(nuevoPersonal.getEstado());
        jTextField2.setText(nuevoPersonal.getNombreImg());
        jTextField2.setText(nuevoPersonal.getRutaImagen());
        //Obtener el nombre la imagen
        String fil = jTextField2.getText();
        //Obtener la direccion donde se guarda la imagen
        String file = jTextField1.getText();
        jLabel18.setIcon(new ImageIcon(fil));
        //Modificar la imagen
        ImageIcon icon = new ImageIcon(fil);
        //Extraer la imagen del icono
        Image img = icon.getImage();
        //Cambiar tamaño a la imagen       
        Image newimg = img.getScaledInstance(153, 160, java.awt.Image.SCALE_SMOOTH);
        //Se genera el ImageIcon con la nueva imagen
        ImageIcon newIcon = new ImageIcon(newimg);
        jLabel18.setIcon(newIcon);

    }

    public void ActivarCampos() {
        combTipoDoc.setEnabled(true);
        txtDocum.setEnabled(true);
        txtNombreC.setEnabled(true);
        DateFechadeN.setEnabled(true);
        CombCiudaddeN.setEnabled(true);
        CombDep.setEnabled(true);
        combTipodeS.setEnabled(true);
        combmasymenos.setEnabled(true);
        txtCargo.setEnabled(true);
        DateFechaC.setEnabled(true);
        txtTipodeCon.setEnabled(true);
        txtDirecciondeR.setEnabled(true);
        txtBarrio.setEnabled(true);
        txtTelefonoF.setEnabled(true);
        txtTelefonoM.setEnabled(true);
        txtCorreoE.setEnabled(true);
        combEstado.setEnabled(true);
    }

    public void DesactivarCampos() {
        combTipoDoc.setEnabled(false);
        txtDocum.setEnabled(false);
        txtNombreC.setEnabled(false);
        DateFechadeN.setEnabled(false);
        CombCiudaddeN.setEnabled(false);
        CombDep.setEnabled(false);
        combTipodeS.setEnabled(false);
        combmasymenos.setEnabled(false);
        txtCargo.setEnabled(false);
        DateFechaC.setEnabled(false);
        txtTipodeCon.setEnabled(false);
        txtDirecciondeR.setEnabled(false);
        txtBarrio.setEnabled(false);
        txtTelefonoF.setEnabled(false);
        txtTelefonoM.setEnabled(false);
        txtCorreoE.setEnabled(false);
        combEstado.setEnabled(false);

    }

    public void ValidarCampos() {

        txtDocum.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(10, txtDocum, e);
                v.soloNumeros(txtDocum, e);
                v.Obligatorios(txtDocum, e);
            }
        });

        this.txtNombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(40, txtNombreC, e);
                v.soloLetras(txtNombreC, e);
                v.Obligatorios(txtNombreC, e);
            }
        });

        this.txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(40, txtCargo, e);
                v.soloLetras(txtCargo, e);
                v.Obligatorios(txtCargo, e);
            }
        });

        this.txtTipodeCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(40, txtTipodeCon, e);
                //v.soloLetras(txtTipodeCon, e);
                v.Obligatorios(txtTipodeCon, e);
            }
        });

        this.txtDirecciondeR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(13, txtTipodeCon, e);
                v.Obligatorios(txtDirecciondeR, e);

            }
        });

        this.txtBarrio.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(18, txtBarrio, e);
                v.soloLetras(txtBarrio, e);
            }
        });

        this.txtTelefonoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(10, txtTelefonoF, e);
                v.soloNumeros(txtTelefonoF, e);
                v.Obligatorios(txtTelefonoF, e);
            }
        });

        this.txtTelefonoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(10, txtTelefonoM, e);
                v.soloNumeros(txtTelefonoM, e);
                v.Obligatorios(txtTelefonoM, e);
            }
        });

        this.txtCorreoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(20, txtCorreoE, e);
                v.Obligatorios(txtCorreoE, e);
            }
        });

    }

    private String ValidarObligatorios() {
        String s = "";
        nuevoPersonal = this.GuardarCampos();
        if (nuevoPersonal.getTipodeDocumento().equals("") || nuevoPersonal.getDocumento().equals("")
                || nuevoPersonal.getNombreCompleto().equals("") || nuevoPersonal.getFechadeNacimiento().equals("")
                || nuevoPersonal.getTipodeSangre().equals("") || nuevoPersonal.getFactorRH().equals("")
                || nuevoPersonal.getCargo().equals("") || nuevoPersonal.getFecha_Contra().equals("")
                || nuevoPersonal.getTipodeContrato().equals("")
                || nuevoPersonal.getDirecciondeResidencia().equals("")
                || nuevoPersonal.getTelefonoFijo().equals("")
                || nuevoPersonal.getTelefonoMovil().equals("")
                || nuevoPersonal.getCorreoElectronico().equals("")) {
            s = "Complete todos los campos obligatorios";
        }

        return s;
    }

}
