package black.white;

import CrudBd.CrudAsignarPerfil;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import listas.ListaPerfil;
import listas.ListaRegistroPersonal;
import logica.MetodosPerfil;
import Utilidades.ReporteCliente;
import Utilidades.ReportePerfil;
import Utilidades.ValidacionesCampos;
import javax.swing.ImageIcon;

public class GestionarPerfil extends javax.swing.JFrame {

    String Docum;
    int swModificar = 0;
    ValidacionesCampos v = new ValidacionesCampos();
    MetodosPerfil nuevoPerfil = new MetodosPerfil();
    MetodosPerfil buscarPerfil = new MetodosPerfil();
    ListaPerfil listaPerfil;
    ListaRegistroPersonal listaPersonal;
    int[] controlContra = new int[4];
    ImageIcon imaPregunta = new ImageIcon("C:\\Boutique\\src\\Imagenes\\pregun.jpg");
    ImageIcon imaInforma = new ImageIcon("C:\\Boutique\\src\\Imagenes\\iconoInfor.jpg");
    String ventana = "Gestionar Perfil - S.I.C";
    CrudAsignarPerfil basePerfil;

    public GestionarPerfil() {
        initComponents();
        basePerfil = new CrudAsignarPerfil();
        setLocationRelativeTo(null);
        setResizable(false);
        this.ValidarCampos();        //this.ValidarObligatorios();
        this.DesactivarCampos();
        this.setVisible(true);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/cliente.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreusu = new javax.swing.JTextField();
        txtIdAsignarPer = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        combPerf = new javax.swing.JComboBox();
        pswContra = new javax.swing.JPasswordField();
        pswConfCont = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar Perfiles");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Id Perfil");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("(*)Confirmar Contraseña:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("(*)Nombre de Usuario:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("(*)Documento:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("(*)Contraseña:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("(*)Perfil:");

        txtNombreusu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreusuFocusLost(evt);
            }
        });
        txtNombreusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreusuActionPerformed(evt);
            }
        });

        txtIdAsignarPer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdAsignarPerFocusLost(evt);
            }
        });
        txtIdAsignarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAsignarPerActionPerformed(evt);
            }
        });

        txtDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDocumentoFocusLost(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.jpg"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnModificar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnModificar.setPreferredSize(new java.awt.Dimension(89, 33));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.jpg"))); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.setMaximumSize(new java.awt.Dimension(40, 40));
        btnCrear.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.jpg"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnGuardar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnGuardar.setPreferredSize(new java.awt.Dimension(89, 33));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultar.jpg"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnConsultar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnConsultar.setPreferredSize(new java.awt.Dimension(89, 33));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/400px-borrar_svg.jpg"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(89, 33));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.jpg"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.jpg"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listar.jpg"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.setMaximumSize(new java.awt.Dimension(40, 40));
        btnListar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        combPerf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMINISTRADOR", "BODEGA", "VENDEDOR" }));

        pswContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswContraFocusLost(evt);
            }
        });
        pswContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswContraActionPerformed(evt);
            }
        });
        pswContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswContraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswContraKeyTyped(evt);
            }
        });

        pswConfCont.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswConfContFocusLost(evt);
            }
        });
        pswConfCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswConfContActionPerformed(evt);
            }
        });
        pswConfCont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswConfContKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Los Campos marcados con (*) son Obligatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdAsignarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combPerf, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(pswConfCont, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNombreusu)
                                        .addGap(23, 23, 23))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(384, 384, 384)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnConsultar, btnCrear, btnEliminar, btnGuardar, btnLimpiar, btnListar, btnModificar, btnSalir});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combPerf, pswContra, txtIdAsignarPer});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdAsignarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(combPerf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreusu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswConfCont, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combPerf, pswContra, txtDocumento, txtIdAsignarPer, txtNombreusu});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsultar, btnCrear, btnEliminar, btnGuardar, btnLimpiar, btnListar, btnModificar, btnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreusuActionPerformed

    private void txtIdAsignarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAsignarPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAsignarPerActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        nuevoPerfil = this.GuardarCampos();
        if (this.ValidacionesObligatorios().equals("")) {

            if (swModificar == 1) {

                if (basePerfil.actualizarPerfil(nuevoPerfil)) {      //se llama desde un condicional ya q retorna un true o un false

                    JOptionPane.showMessageDialog(this, "Se Guardó la Modificación Correctamente", "Gestionar Perfil - S.I.C ",
                            JOptionPane.OK_OPTION, imaInforma);
                    this.LimpiarCampos();
                    this.DesactivarCampos();
                    swModificar = 0;
                    btnGuardar.setEnabled(false);
                    this.activarBotones();

                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo guardar la Modificación Correctamente", "Gestionar Perfil - S.I.C ",
                            JOptionPane.OK_OPTION, imaInforma);
                }

            } else {

                if (basePerfil.siExiste(nuevoPerfil.getNumDoc())) {

                    JOptionPane.showMessageDialog(this, "Este Perfil ya Existe", "Gestionar Perfil - S.I.C ",
                            JOptionPane.OK_OPTION, imaInforma);

                } else {

                    if (basePerfil.asignarPerfil(nuevoPerfil)) {
                        JOptionPane.showMessageDialog(this, "Se guardó correctamente", "Gestionar Perfil - S.I.C ",
                                JOptionPane.OK_OPTION, imaInforma);
                        this.LimpiarCampos();
                        this.DesactivarCampos();
                        btnGuardar.setEnabled(false);
                        this.activarBotones();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se guardó", "Gestionar Perfil - S.I.C ",
                                JOptionPane.OK_OPTION, imaInforma);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese Los Campos Obligatorios", "Gestionar Perfil - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        swModificar = 0;
        this.desactivarBotones();
        this.ActivarCampos();
        this.LimpiarCampos();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.llenarDatos();
        this.ActivarCampos();
        swModificar = 1;
        txtIdAsignarPer.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        this.llenarDatos();
        this.DesactivarCampos();
        swModificar = 0;
        this.activarBotones();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.activarBotones();
        this.LimpiarCampos();
        this.DesactivarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String PerfilaEliminar = JOptionPane.showInputDialog(this, "Ingrese el número de documento ha eliminar");
        if (basePerfil.eliminarPerfil(Integer.parseInt(PerfilaEliminar))) {
            JOptionPane.showMessageDialog(this, "Se eliminó correctamente", "Gestionar Cliente - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
            this.LimpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "El perfil no existe!", "Gestionar Cliente - S.I.C ",
                    JOptionPane.OK_OPTION, imaInforma);
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ReportePerfil rpe = new ReportePerfil(listaPerfil.getCabeza());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opc;
        opc = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir ?",
                "Salir.  Sistema Integral Comercial - S.I.C", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, imaPregunta);
        if (opc == 0) {
            this.setVisible(false);

        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void pswContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContraActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_pswContraActionPerformed

    private void pswContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswContraKeyPressed

// TODO add your handling code here:
    }//GEN-LAST:event_pswContraKeyPressed

    private void pswContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswContraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pswContraKeyTyped

    private void pswConfContKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswConfContKeyPressed

// TODO add your handling code here:
    }//GEN-LAST:event_pswConfContKeyPressed

    private void txtIdAsignarPerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdAsignarPerFocusLost

        if (txtIdAsignarPer.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Este campo es obligatorio", "Gestionar Perfil - S.I.C", JOptionPane.YES_OPTION, imaInforma);
            txtIdAsignarPer.requestFocusInWindow();
        } else {
            if (basePerfil.siExiste(Integer.parseInt(txtIdAsignarPer.getText()))) {
                JOptionPane.showMessageDialog(null, "Este documento ya tiene un perfil asignado", "Gestionar Perfil - S.I.C", JOptionPane.YES_OPTION, imaInforma);
                txtIdAsignarPer.requestFocusInWindow();
                txtIdAsignarPer.setText("");
            } else {
                txtIdAsignarPer.transferFocus();
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_txtIdAsignarPerFocusLost

    private void txtNombreusuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreusuFocusLost

     /*   if (txtNombreusu.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Este campo es obligatorio", "Gestionar Perfil - S.I.C", JOptionPane.YES_OPTION, imaInforma);
            txtNombreusu.requestFocusInWindow();
        } else {
            if (listaPerfil.siExisteUsuario(txtNombreusu.getText())) {
                JOptionPane.showMessageDialog(null, "Este nombre de usuario ya existe", "Gestionar Perfil - S.I.C", JOptionPane.YES_OPTION, imaInforma);
                txtNombreusu.requestFocusInWindow();
                txtNombreusu.setText("");
            } else {
                txtNombreusu.transferFocus();
            }

        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreusuFocusLost

    private void pswConfContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswConfContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswConfContActionPerformed

    private void pswConfContFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswConfContFocusLost

        if (pswConfCont.getPassword().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Este es un campo obligatorio", "Gestionar Perfil - S.I.C", JOptionPane.YES_OPTION, imaInforma);
        } else {
            if (!pswContra.getText().equals(pswConfCont.getText())) {

                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Gestionar Perfil - S.I.C", JOptionPane.OK_OPTION, null);
                pswConfCont.requestFocus();
            } else {
                if (!ValidacionesObligatorios().equals("")) {
                btnGuardar.setEnabled(true);
                btnGuardar.requestFocusInWindow();
                this.DesactivarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Digite todos los campos obligatorios", "Gestionar Perfil - S.I.C.", JOptionPane.OK_OPTION, imaInforma);
                pswConfCont.transferFocus();
            }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pswConfContFocusLost

    private void pswContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswContraFocusLost

    /*    if (pswContra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Este es un campo obligatorio", "Gestionar Perfil - S.I.C", JOptionPane.YES_OPTION, imaInforma);
        } else {
            String pasword = new String(pswContra.getPassword());
            if (!v.validarContraseñ(pasword)) {

                JOptionPane.showMessageDialog(null, "Debe contener al menos :" + "\n" + "1 caracter especial" + "\n"
                        + "1 letra mayúscula" + "\n" + " 1 letra minúscula" + "\n" + "1 número"
                        + "\n" + "mínimo 8 caracteres", "Gestionar Perfil - S.I.C", JOptionPane.OK_OPTION, null);
                pswContra.requestFocus();
            } else {
                if (listaPerfil.siExisteContra(pswContra.getText())) {
                    JOptionPane.showMessageDialog(null, "Esta contraseña ya existe", "Gestionar Perfil - S.I.C", JOptionPane.YES_OPTION, imaInforma);
                    pswContra.requestFocusInWindow();
                    pswContra.setText("");
                } else {
                    pswContra.transferFocus();
                }
            }
        }*/
// TODO add your handling code here:
    }//GEN-LAST:event_pswContraFocusLost

    private void txtDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDocumentoFocusLost

        if (txtDocumento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Este es un campo obligatorio", "Gestionar Perfil - S.I.C.", JOptionPane.OK_OPTION, imaInforma);
            txtDocumento.requestFocusInWindow();
        } 

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox combPerf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField pswConfCont;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtIdAsignarPer;
    private javax.swing.JTextField txtNombreusu;
    // End of variables declaration//GEN-END:variables
public void LimpiarCampos() {

        txtIdAsignarPer.setText("");
        txtNombreusu.setText("");
        pswConfCont.setText("");
        combPerf.setSelectedItem("");
        pswContra.setText("");
        txtDocumento.setText("");
    }

    public MetodosPerfil GuardarCampos() {
        MetodosPerfil Mp = new MetodosPerfil();
        Mp.setIdPerfil(Integer.parseInt(txtIdAsignarPer.getText()));
        Mp.setNumDoc(Integer.parseInt(txtDocumento.getText()));
        Mp.setPerf(combPerf.getSelectedIndex());
        Mp.setContra(pswContra.getText());
        Mp.setConfContra(pswConfCont.getText());
        Mp.setNombreUsu(txtNombreusu.getText());
        Mp.setFecha(new Date());
        return Mp;
    }

    public void llenarDatos() {

        int opc = -2;
        String[] opciones = {"Número de Documento", "Nombre de Usuario"};
        if (swModificar == 1) {

            buscarPerfil = basePerfil.consultarPerfil(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de documento del perfil a modificar")));
        } else {

            opc = JOptionPane.showOptionDialog(null, "Seleccione la forma en que desea realizar la consulta",
                    "Consulta Perfiles. S.I.C.", JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE, imaPregunta, opciones, true);
            switch (opc) {

                case 0:
                    buscarPerfil = basePerfil.consultarPerfil(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el número de documento del perfil a consultar")));
                    break;
                case 1:

                    //buscarPerfil = basePerfil.BuscarPerfilNomUsuario(JOptionPane.showInputDialog("Ingrese el nombre de usuario del perfil a consultar"));
                    break;
            }
        }
        if (opc != -1) {
            if (buscarPerfil != null) {
                txtIdAsignarPer.setText(String.valueOf(buscarPerfil.getIdPerfil()));
                txtNombreusu.setText(buscarPerfil.getNombreusu());
                pswContra.setText(buscarPerfil.getContra());
                combPerf.setSelectedIndex(buscarPerfil.getPerf());
                pswConfCont.setText(buscarPerfil.getContra());
                txtDocumento.setText(buscarPerfil.getResp());
                this.desactivarBotones();
            } else {

                JOptionPane.showMessageDialog(null, "El perfil no existe", "Gestionar Perfil - S.I.C",
                        JOptionPane.OK_OPTION, imaInforma);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Se canceló la consulta", "Gestionar Perfil - S.I.C",
                    JOptionPane.OK_OPTION, imaInforma);
        }

        buscarPerfil = null;
    }

    public void ActivarCampos() {
        txtIdAsignarPer.setEnabled(true);
        txtNombreusu.setEnabled(true);
        pswContra.setEnabled(true);
        combPerf.setEnabled(true);
        pswConfCont.setEnabled(true);
        txtDocumento.setEnabled(true);

    }

    public void DesactivarCampos() {
        txtIdAsignarPer.setEnabled(false);
        txtNombreusu.setEnabled(false);
        pswContra.setEnabled(false);
        combPerf.setEnabled(false);
        pswConfCont.setEnabled(false);
        txtDocumento.setEnabled(false);

    }

    public void activarBotones() {

        btnConsultar.setEnabled(true);
        btnCrear.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnListar.setEnabled(true);
        btnSalir.setEnabled(true);
        btnModificar.setEnabled(true);

    }

    public void desactivarBotones() {

        btnConsultar.setEnabled(false);
        btnCrear.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnListar.setEnabled(false);
        btnSalir.setEnabled(false);
        btnModificar.setEnabled(false);

    }

    public void ValidarCampos() {

        txtIdAsignarPer.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(10, txtIdAsignarPer, e);
                v.soloNumeros(txtIdAsignarPer, e);
                v.Obligatorios(txtIdAsignarPer, e);
            }
        });

        this.txtNombreusu.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(40, txtNombreusu, e);
                v.soloLetras(txtNombreusu, e);
                v.Obligatorios(txtNombreusu, e);
            }
        });

        this.pswContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(15, pswContra, e);
                //v.soloLetras(txtTipodeCon, e);
                v.Obligatorios(pswContra, e);
            }
        });

        this.combPerf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(13, pswContra, e);
                v.Obligatorios(pswContra, e);

            }
        });

        this.pswConfCont.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(15, pswConfCont, e);

            }
        });

        //     this.txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
        //      public void keyTyped(java.awt.event.KeyEvent e) {
        //        v.validarLongitud(20, txtCorreo, e);
        //      v.Obligatorios(txtCorreo, e);
        //}
        //});
        this.txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(20, txtDocumento, e);
                v.Obligatorios(txtDocumento, e);
            }
        });
    }

    private String ValidacionesObligatorios() {
        String v = "";
        nuevoPerfil = this.GuardarCampos();

        if (nuevoPerfil.getPerf() == 0
                || String.valueOf(nuevoPerfil.getNumDoc()).equals("")
                || nuevoPerfil.getNombreUsu().equals("") || nuevoPerfil.getContra().equals("")
                || nuevoPerfil.getConfContra().equals("")) {

            v = "Complete todos los campos obligatorios";
        }

        return v;
    }

}
