/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package black.white;

import logica.MetodosRegistro;
import java.util.Date;
import java.text.SimpleDateFormat;
import Utilidades.ValidacionesCampos;
import javax.swing.*;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import logica.MetodosCliente;
import javax.swing.ImageIcon;
import listas.ListeRegistroPedido;
import Utilidades.ReportePedido;

public class Pedido extends javax.swing.JFrame {

    String com;
    double a[], acum = 0;
    int swModificar = 0;
    private Date fecha;
    MetodosRegistro nuevoPedido = new MetodosRegistro();
    ListeRegistroPedido listaRegistroPedido;
    ValidacionesCampos v = new ValidacionesCampos();
    DefaultTableModel tabProd;
    ImageIcon imaPregunta = new ImageIcon("C:\\Boutique\\src\\Imagenes\\pregun.jpg");
    ImageIcon imaInforma = new ImageIcon("C:\\Boutique\\src\\Imagenes\\iconoInfor.jpg");
    String ventana = "Gestionar Pedido - S.I.C";

    public Pedido(ListeRegistroPedido listaPedi) {
        initComponents();
        this.listaRegistroPedido = listaPedi;
        setLocationRelativeTo(null);
        setResizable(false);
        this.validarCamposRegistro();
        this.setVisible(true);
        a = new double[3];
        this.setLocationRelativeTo(null);// para que aparezca en la mitad//
        this.setResizable(false);//para que el tamaño no se modifique//s
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/pedidos.jpg")).getImage());

        tabProd = new DefaultTableModel();
        tabProd.addColumn("Código del Producto");
        tabProd.addColumn("Cantidad");
        tabProd.addColumn("Valor Uniario");
        tabProd.addColumn("Valor Total");
        this.TablaPro.setModel(tabProd);

        this.cmbProveedor.addItem("Escape");
        this.cmbProveedor.addItem("Flamingo");
        this.cmbProveedor.addItem("Agaval");

        this.cmbCodArt.addItem("101");
        this.cmbCodArt.addItem("102");
        this.cmbCodArt.addItem("103");
        this.cmbCodArt.addItem("104");
        this.cmbCodArt.addItem("105");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/pedidos.jpg")).getImage());
        jdFecha.setMaxSelectableDate(new Date());
        
    }

    private Pedido() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCodigo = new javax.swing.JLabel();
        txtCodCompra = new javax.swing.JTextField();
        labRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        labProve = new javax.swing.JLabel();
        labValUni = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        labSub = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        labFact = new javax.swing.JLabel();
        txtFacturaCompra = new javax.swing.JTextField();
        labTel = new javax.swing.JLabel();
        txtNumtel = new javax.swing.JTextField();
        labCel = new javax.swing.JLabel();
        txtNumovil = new javax.swing.JTextField();
        labContac = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        labIva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        labFecha = new javax.swing.JLabel();
        labCodArt = new javax.swing.JLabel();
        labCant = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        labDirec = new javax.swing.JLabel();
        txtDirec = new javax.swing.JTextField();
        labTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jdFecha = new com.toedter.calendar.JDateChooser();
        btnCrear = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cmbCodArt = new javax.swing.JComboBox();
        cmbProveedor = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Pedido");

        labCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labCodigo.setText("Código Compra(*):");

        txtCodCompra.setEnabled(false);
        txtCodCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodCompraFocusLost(evt);
            }
        });
        txtCodCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodCompraActionPerformed(evt);
            }
        });

        labRut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labRut.setText("Rut:");

        txtRut.setEnabled(false);
        txtRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRutFocusLost(evt);
            }
        });
        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        labProve.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labProve.setText("Proveedor(*):");

        labValUni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labValUni.setText("Valor Unitario(*):");

        txtValorUnitario.setEnabled(false);
        txtValorUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorUnitarioFocusLost(evt);
            }
        });
        txtValorUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnitarioActionPerformed(evt);
            }
        });
        txtValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorUnitarioKeyPressed(evt);
            }
        });

        labSub.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labSub.setText("Sub Total:");

        txtSubTotal.setEnabled(false);
        txtSubTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubTotalFocusLost(evt);
            }
        });
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        labFact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labFact.setText("Factura Compra(*):");

        txtFacturaCompra.setEnabled(false);
        txtFacturaCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFacturaCompraFocusLost(evt);
            }
        });
        txtFacturaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaCompraActionPerformed(evt);
            }
        });

        labTel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labTel.setText("Teléfono:");

        txtNumtel.setEnabled(false);
        txtNumtel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumtelFocusLost(evt);
            }
        });
        txtNumtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumtelActionPerformed(evt);
            }
        });

        labCel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labCel.setText("Celular:");

        txtNumovil.setEnabled(false);
        txtNumovil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumovilFocusLost(evt);
            }
        });
        txtNumovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumovilActionPerformed(evt);
            }
        });

        labContac.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labContac.setText("Contacto:");

        txtContacto.setEnabled(false);
        txtContacto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactoFocusLost(evt);
            }
        });
        txtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoActionPerformed(evt);
            }
        });

        labIva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labIva.setText("Iva 16%");

        txtIva.setEnabled(false);
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });

        labFecha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labFecha.setText("Fecha(*):");

        labCodArt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labCodArt.setText("Código Artículo:");

        labCant.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labCant.setText("Cantidad(*):");

        txtCantidad.setEnabled(false);
        txtCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantidadFocusLost(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });

        labDirec.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labDirec.setText("Dirección(*):");

        txtDirec.setEnabled(false);
        txtDirec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDirecFocusLost(evt);
            }
        });
        txtDirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecActionPerformed(evt);
            }
        });

        labTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labTotal.setText("Total:");

        txtTotal.setEnabled(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        jdFecha.setEnabled(false);

        btnCrear.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.jpg"))); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.jpg"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/400px-borrar_svg.jpg"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultar.jpg"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.jpg"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.jpg"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.jpg"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cmbCodArt.setEnabled(false);

        cmbProveedor.setEnabled(false);
        cmbProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbProveedorFocusLost(evt);
            }
        });
        cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorActionPerformed(evt);
            }
        });

        TablaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaPro);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Los Campos marcados con (*) son obligatorios:");

        btnListar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listar.jpg"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labSub, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labDirec)
                            .addComponent(labCodigo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labProve, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labCodArt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCodArt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labIva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCant)
                            .addComponent(labCel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labRut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumovil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFacturaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labContac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labTel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labValUni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumtel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(422, 422, 422))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnConsultar, btnCrear, btnEliminar, btnGuardar, btnLimpiar, btnListar, btnModificar, btnSalir});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbCodArt, txtCantidad});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbProveedor, txtValorUnitario});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labFact, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFacturaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labProve, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labRut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumovil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumtel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labContac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labCant, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labCodArt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbCodArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labValUni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labSub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labIva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsultar, btnCrear, btnEliminar, btnGuardar, btnLimpiar, btnListar, btnModificar, btnSalir});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbCodArt, txtCantidad});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbProveedor, txtValorUnitario});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodCompraActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtValorUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitarioActionPerformed


    }//GEN-LAST:event_txtValorUnitarioActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtFacturaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaCompraActionPerformed

    private void txtNumtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumtelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumtelActionPerformed

    private void txtNumovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumovilActionPerformed

    private void txtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtDirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.DesactivarCampos();
        this.ActivarCampos();
        this.desactivarBotones();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        nuevoPedido = this.GuardarCampos();
        if (this.validacionObligatorios().equals("")) {
            if (swModificar == 1) {
                if (listaRegistroPedido.guardarModificacionPedido(nuevoPedido)) {
                    JOptionPane.showMessageDialog(this, "Se modificó el pedido correctamente", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                            imaInforma);
                    this.LimpiarCampos();
                    this.DesactivarCampos();
                    swModificar = 0;
                    btnGuardar.setEnabled(false);
                    this.activarBotones();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo modificar el pedido correctamente", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                            imaInforma);

                }
            } else {
                if (listaRegistroPedido.siExiste(nuevoPedido.getCodCompr())) {

                    JOptionPane.showMessageDialog(this, "El Pedido ya existe", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                            imaInforma);

                } else {

                    if (listaRegistroPedido.GuardarRegistroPedido(nuevoPedido)) {
                        JOptionPane.showMessageDialog(this, "Se guardó el pedido correctamente", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                                imaInforma);
                         btnGuardar.setEnabled(false);
                         this.activarBotones();
                    } else {
                        JOptionPane.showMessageDialog(this, "No pudo ser guardado ", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                                imaInforma);
                    }
                    this.LimpiarCampos();
                    this.DesactivarCampos();
                }
            }

        } else {

            JOptionPane.showMessageDialog(this, "Ingrese los campos Obligatorios", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                    imaInforma);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.LimpiarCampos();
        this.DesactivarCampos();
        this.activarBotones();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        String PerfilaConsultar = JOptionPane.showInputDialog(this, "Ingrese el código de la compra");
        nuevoPedido = listaRegistroPedido.buscarPedido(PerfilaConsultar);
        if (nuevoPedido == null) {

            JOptionPane.showMessageDialog(this, "El código de la compra no existe", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                    imaInforma);
        } else {
            this.LlenarDatos();
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String pedidoaModificar = JOptionPane.showInputDialog(this, "Ingrese el código del producto");
        if (listaRegistroPedido.siExiste(pedidoaModificar)) {
            nuevoPedido = listaRegistroPedido.buscarPedido(pedidoaModificar);
            this.LlenarDatos();
            this.ActivarCampos();
            swModificar = 1;
            this.desactivarBotones();
        } else {

            JOptionPane.showMessageDialog(this, "El código de la compra ingresado no esta registrado ", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                    imaInforma);

        }
        txtCodCompra.setEnabled(false);
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String pedidoaEliminar = JOptionPane.showInputDialog(this, "Ingrese el código de la compra ha eliminar");
        if (listaRegistroPedido.eliminarPedido(pedidoaEliminar)) {
            JOptionPane.showMessageDialog(this, "Se eliminó el pedido correctamente", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                    imaInforma);
        } else {
            JOptionPane.showMessageDialog(this, "No existe el pedido", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                    imaInforma);
        }
        this.LimpiarCampos();

// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opc;
        opc = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir ?",
                "Salir.  Sistema Integral Comercial - S.I.C.", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, imaPregunta);
        if (opc == 0) {
            this.setVisible(false);

        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed


    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtValorUnitarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnitarioKeyPressed

        

    }//GEN-LAST:event_txtValorUnitarioKeyPressed

    private void cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedorActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ReportePedido rped = new ReportePedido(listaRegistroPedido.getcabeza());
    }//GEN-LAST:event_btnListarActionPerformed

    private void txtCodCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodCompraFocusLost
        if (txtCodCompra.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Este campo es obligatorio", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                    imaInforma);
        } else {
            if (listaRegistroPedido.siExiste(txtCodCompra.getText())) {
                JOptionPane.showMessageDialog(this, "Este código ya existe", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                        imaInforma);
            } else {
                txtCodCompra.transferFocus();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodCompraFocusLost

    private void txtFacturaCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFacturaCompraFocusLost
        v.validarObligatorios(txtFacturaCompra, ventana);

        // TODO add your handling code here:t
    }//GEN-LAST:event_txtFacturaCompraFocusLost

    private void cmbProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbProveedorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedorFocusLost

    private void txtRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutFocusLost
        v.validarObligatorios(txtRut, ventana);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutFocusLost

    private void txtNumtelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumtelFocusLost
        v.validarObligatorios(txtNumtel, ventana);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumtelFocusLost

    private void txtDirecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDirecFocusLost
        v.validarObligatorios(txtDirec, ventana);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecFocusLost

    private void txtNumovilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumovilFocusLost
        v.validarObligatorios(txtNumovil, ventana);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumovilFocusLost

    private void txtContactoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactoFocusLost
        v.validarObligatorios(txtContacto, ventana);
// TODO add your handling code here:
    }//GEN-LAST:event_txtContactoFocusLost

    private void txtCantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantidadFocusLost
        v.validarObligatorios(txtCantidad, ventana);
// TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadFocusLost

    private void txtValorUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorUnitarioFocusLost
        if (txtValorUnitario.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Este campo es obligatorio", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                    imaInforma);
            txtValorUnitario.requestFocusInWindow();
        } else {
            a = Sumatoria(txtCantidad, txtValorUnitario);
            txtSubTotal.setText(Double.toString(a[0]));
            txtIva.setText(Double.toString(a[1]));
            txtTotal.setText(Double.toString(a[2]));
            acum = acum + a[2];
            if (validacionObligatorios().equals("")) {
                btnGuardar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Digite todos los campos obligatorios", "Gestionar Pedido - S.I.C", JOptionPane.OK_OPTION,
                        imaInforma);
                txtValorUnitario.requestFocusInWindow();
            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitarioFocusLost
    private void txtSubTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubTotalFocusLost

// TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalFocusLost

    /**
     * f
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPro;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbCodArt;
    private javax.swing.JComboBox cmbProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JLabel labCant;
    private javax.swing.JLabel labCel;
    private javax.swing.JLabel labCodArt;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labContac;
    private javax.swing.JLabel labDirec;
    private javax.swing.JLabel labFact;
    private javax.swing.JLabel labFecha;
    private javax.swing.JLabel labIva;
    private javax.swing.JLabel labProve;
    private javax.swing.JLabel labRut;
    private javax.swing.JLabel labSub;
    private javax.swing.JLabel labTel;
    private javax.swing.JLabel labTotal;
    private javax.swing.JLabel labValUni;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodCompra;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JTextField txtFacturaCompra;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNumovil;
    private javax.swing.JTextField txtNumtel;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables

    public void LimpiarCampos() {

        txtCodCompra.setText("");
        txtContacto.setText("");
        txtDirec.setText("");
        txtIva.setText("");
        txtFacturaCompra.setText("");
        txtNumovil.setText("");
        txtNumtel.setText("");
        txtTotal.setText("");
        txtCantidad.setText("");
        txtSubTotal.setText("");
        txtRut.setText("");
        txtValorUnitario.setText("");
        cmbCodArt.setSelectedItem(null);
        cmbProveedor.setSelectedItem(null);
        jdFecha.setDate(null);
    }

    public MetodosRegistro GuardarCampos() {
        MetodosRegistro p2 = new MetodosRegistro();
        p2.setCodCompr((String) txtCodCompra.getText());
        p2.setContacto((String) txtContacto.getText());
        p2.setDirec((String) txtDirec.getText());
        p2.setIva((String) txtIva.getText());
        p2.setSubTotal((String) txtSubTotal.getText());
        p2.setRut((String) txtRut.getText());
        p2.setValorUnit((String) txtValorUnitario.getText());
        p2.setCodArt((String) cmbCodArt.getSelectedItem());
        p2.setProveedor((String) cmbProveedor.getSelectedItem());
        p2.setFactCompra((String) txtFacturaCompra.getText());
        p2.setNumMovil((String) txtNumovil.getText());
        p2.setNumTel((String) txtNumtel.getText());
        p2.setTotal((String) txtTotal.getText());
        p2.setCantidad((String) txtCantidad.getText());
        p2.setFecha(jdFecha.getDate());
        return p2;

    }

    public void LlenarDatos() {

        txtCodCompra.setText(nuevoPedido.getCodCompr());
        txtFacturaCompra.setText(nuevoPedido.getFactCompra());
        txtNumovil.setText(nuevoPedido.getNumMovil());
        txtContacto.setText(nuevoPedido.getContacto());
        txtNumtel.setText(nuevoPedido.getNumTel());
        txtCantidad.setText(nuevoPedido.getCantidad());
        txtDirec.setText(nuevoPedido.getDirec());
        txtIva.setText(nuevoPedido.getIva());
        txtSubTotal.setText(nuevoPedido.getSubTotal());
        txtRut.setText(nuevoPedido.getRut());
        txtValorUnitario.setText(nuevoPedido.getValorUnit());
        cmbCodArt.setSelectedItem(nuevoPedido.getCodArt());
        cmbProveedor.setSelectedItem(nuevoPedido.getProveedor());
        jdFecha.setDate(nuevoPedido.getFecha());
        txtTotal.setText(nuevoPedido.getTotal());

    }

    public void ActivarCampos() {

        txtCodCompra.setEnabled(true);
        txtFacturaCompra.setEnabled(true);
        txtNumovil.setEnabled(true);
        txtContacto.setEnabled(true);
        txtNumtel.setEnabled(true);
        txtCantidad.setEnabled(true);
        txtDirec.setEnabled(true);
        txtRut.setEnabled(true);
        txtValorUnitario.setEnabled(true);
        cmbCodArt.setEnabled(true);
        cmbProveedor.setEnabled(true);
        jdFecha.setEnabled(true);

    }

    public void DesactivarCampos() {

        txtCodCompra.setEnabled(false);
        txtFacturaCompra.setEnabled(false);
        txtNumovil.setEnabled(false);
        txtContacto.setEnabled(false);
        txtNumtel.setEnabled(false);
        txtCantidad.setEnabled(false);
        txtDirec.setEnabled(false);
        txtIva.setEnabled(false);
        txtSubTotal.setEnabled(false);
        txtRut.setEnabled(false);
        txtValorUnitario.setEnabled(false);
        cmbCodArt.setEnabled(false);
        cmbProveedor.setEnabled(false);
        jdFecha.setEnabled(false);
        txtTotal.setEnabled(false);
        
    }
        
        public void activarBotones() {

        btnConsultar.setEnabled(true);
        btnCrear.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnListar.setEnabled(true);
        btnSalir.setEnabled(true);
        btnModificar.setEnabled(true);

    }

    public void desactivarBotones() {

        btnConsultar.setEnabled(false);
        btnCrear.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnListar.setEnabled(false);
        btnSalir.setEnabled(false);
        btnModificar.setEnabled(false);

    

    }

    private String validacionObligatorios() {

        String s = "";
        nuevoPedido = this.GuardarCampos();
        if (nuevoPedido.getCodArt().equals("")) {
            s = "Complete Todos Los Campos Obligatorios";
        }

        return s;
    }

    public void validarCamposRegistro() {
        txtCodCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(5, txtCodCompra, e);
                v.soloNumeros(txtCodCompra, e);
            }
        });

        this.txtFacturaCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(5, txtFacturaCompra, e);
                v.soloNumeros(txtFacturaCompra, e);
            }
        });
        this.txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(15, txtRut, e);
                v.soloNumeros(txtRut, e);
            }
        });

        this.txtNumtel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(7, txtNumtel, e);
                v.soloNumeros(txtNumtel, e);
            }
        });

        this.txtNumovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(10, txtNumovil, e);
                v.soloNumeros(txtNumovil, e);
            }
        });
        this.txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(3, txtCantidad, e);
                v.soloNumeros(txtCantidad, e);
            }
        });

        this.txtValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent e) {
                v.validarLongitud(6, txtValorUnitario, e);
                v.soloNumeros(txtValorUnitario, e);
            }
        });
    }

    public double[] Sumatoria(JTextField c, JTextField v) {

        String cantidad, valor;
        double r[];
        r = new double[3];

        cantidad = c.getText();
        valor = v.getText();

        int can = Integer.parseInt(cantidad);
        int val = Integer.parseInt(valor);

        r[0] = can * val;
        r[1] = r[0] * 0.16;
        r[2] = r[0] + r[1];

        return r;
    }

}
